entity.config_pages.collection:
  title: 'Config pages'
  route_name: entity.config_pages.collection
  base_route: block.admin_display
config_pages.list_sub:
  title: Blocks
  route_name: entity.config_pages.collection
  parent_id: entity.config_pages.collection
entity.config_pages_type.collection:
  title: Types
  route_name: entity.config_pages_type.collection
  parent_id: entity.config_pages.collection
  weight: 1

entity.config_pages.canonical:
  title: Edit
  route_name: entity.config_pages.canonical
  base_route: entity.config_pages.canonical
entity.config_pages.delete_form:
  title: Delete
  route_name: entity.config_pages.delete_form
  base_route: entity.config_pages.canonical

# Default tab for custom block type editing.
entity.config_pages_type.edit_form:
  title: 'Edit'
  route_name: entity.config_pages_type.edit_form
  base_route: entity.config_pages_type.edit_form
