entity.config_pages_type.collection:
  path: '/admin/structure/config_pages_types'
  defaults:
    _controller: '\Drupal\Core\Entity\Controller\EntityListController::listing'
    entity_type: 'config_pages_type'
    _title: 'Config pages types'
  requirements:
    _permission: 'administer content types'

config_pages.type_add:
  path: '/admin/structure/config_pages/add'
  defaults:
    _entity_form: 'config_pages_type.add'
    _title: 'Add config page'
  requirements:
    _permission: 'administer content types'
