<?php
/**
 * @file
 * Module hooks.
 */

// Define const for ConfigPage entity type.
const CONFIG_PAGES_ENTITY_TYPE = 'config_pages_type';

use Drupal\config_pages\Entity\ConfigPages;
use Drupal\config_pages\Entity\ConfigPagesType;

/**
 * @param string
 *  config_page type to get context.
 *
 * @return array
 *  Return current context based on groups.
 */
function config_pages_context_get($type) {
  $context = [];
  $type = ConfigPagesType::getTypes($type);
  if (!$type) {
    return $context;
  }

  $context = $type->getContextData();

  return $context;
}
