entity.config_pages_type.collection:
  path: '/admin/structure/config_pages_types'
  defaults:
    _controller: '\Drupal\Core\Entity\Controller\EntityListController::listing'
    entity_type: 'config_pages_type'
    _title: 'Config pages types'
  requirements:
    _permission: 'administer content types'

config_pages.type_add:
  path: '/admin/structure/config_pages/add'
  defaults:
    _entity_form: 'config_pages_type.add'
    _title: 'Add config page'
  requirements:
    _permission: 'administer content types'

entity.config_pages.canonical:
  path: '/admin/structure/config_pages/{config_pages}'
  defaults:
    _entity_view: 'config_pages'
    _title: 'Config page'
  requirements:
    _entity_access: 'config_pages.view'

entity.config_pages_type.edit_form:
  path: '/admin/structure/config_pages_type/manage/{config_pages_type}'
  defaults:
    _entity_form: 'config_pages_type.edit'
  requirements:
    _permission: 'administer content types'
