entity.config_pages_type.collection:
  path: '/admin/structure/config_pages/config-pages-content/types'
  defaults:
    _entity_list: 'config_pages_type'
    _title: 'Custom block library'
  requirements:
    _permission: 'administer blocks'

config_pages.add_page:
  path: '/config_pages/add'
  defaults:
    _controller: '\Drupal\config_pages\Controller\ConfigPagesController::add'
    _title: 'Add custom block'
  options:
    _admin_route: TRUE
  requirements:
    _permission: 'administer blocks'

config_pages.add_form:
  path: '/config_pages/add/{config_pages_type}'
  defaults:
    _controller: '\Drupal\config_pages\Controller\ConfigPagesController::addForm'
    _title_callback: 'Drupal\config_pages\Controller\ConfigPagesController::getAddFormTitle'
  options:
    _admin_route: TRUE
  requirements:
    _permission: 'administer blocks'

entity.config_pages_type.delete_form:
  path: '/admin/structure/config_pages/config-pages-content/manage/{config_pages_type}/delete'
  defaults:
    _entity_form: 'config_pages_type.delete'
    _title: 'Delete'
  requirements:
    _entity_access: 'config_pages_type.delete'
  options:
    _admin_route: TRUE

entity.config_pages.canonical:
  path: '/config_pages/{config_pages}'
  defaults:
    _entity_form: 'config_pages.edit'
  options:
    _admin_route: TRUE
  requirements:
    _entity_access: 'config_pages.update'

entity.config_pages.edit_form:
  path: '/config_pages/{config_pages}'
  defaults:
    _entity_form: 'config_pages.edit'
  options:
    _admin_route: TRUE
  requirements:
    _entity_access: 'config_pages.update'

entity.config_pages.delete_form:
  path: '/config_pages/{config_pages}/delete'
  defaults:
    _entity_form: 'config_pages.delete'
    _title: 'Delete'
  options:
    _admin_route: TRUE
  requirements:
    _entity_access: 'config_pages.delete'

config_pages.type_add:
  path: '/admin/structure/config_pages/config-pages-content/types/add'
  defaults:
    _entity_form: 'config_pages_type.add'
    _title: 'Add'
  requirements:
    _permission: 'administer blocks'

entity.config_pages_type.edit_form:
  path: '/admin/structure/config_pages/config0pages-content/manage/{config_pages_type}'
  defaults:
    _entity_form: 'config_pages_type.edit'
    _title: 'Edit'
  requirements:
    _entity_access: 'config_pages_type.update'

entity.config_pages.collection:
  path: '/admin/structure/config_pages/config-pages'
  defaults:
    _title: 'Custom block library'
    _entity_list: 'config_pages'
  requirements:
    _permission: 'administer blocks'
