# Schema for the configuration files of the Custom Block module.

config_pages.type.*:
  type: config_entity
  label: 'Config page type settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
