<?php

/**
 * @file
 * Contains mks_custom_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mks_custom_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mks_custom_entity module.
    case 'help.page.mks_custom_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MKS custom entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mks_custom_entity_theme() {
  $theme = [];

  return $theme;
}
