<?php

/**
 * @file
 * Contains site_common.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_common_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_common module.
    case 'help.page.site_common':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Site common module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function site_common_theme() {
  $theme = [];

  return $theme;
}
